server:
  port:  8080

multiple:
  db01:
    url: jdbc:mysql://101.132.40.203:3306/test1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    minPoolSize: 3
    maxPoolSize: 25
    maxLifetime: 20000
    borrowConnectionTimeout: 30
    loginTimeout: 30
    maintenanceInterval: 60
    maxIdleTime: 60
    testQuery: select 1
  db02:
      url: jdbc:mysql://101.132.40.203:3306/test
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://101.132.40.203:3306/test1
#    username: root
#    password: 123456